alfworld-vision:
  env_name: alfworld
  env_config:
    render_mode: vision
    alf_config_path: "scripts/benchmark/service_benchmark/alfworld/alf-config.yaml"
    max_actions_per_step: 1
  train_size: 1000
  test_size: 64
