defaults:
  - _self_


use_llm_judge: False

server:
  host: 0.0.0.0
  port: 5000
  debug: false

frozenlake:
  max_workers: 48
svg:
  max_workers: 48
  model_size: "small"
  device:
    dino: 1
    service: 2
navigation:
  max_workers: 48
  devices: [0,1,2,3]
primitive_skill:
  max_workers: 48

