env1:
    env_name: primitive_skill 
    env_config:
        render_mode: vision
        prompt_format: grounding_worldmodeling_structured
        use_state_reward: true
        grounding_reward_weight: 100
        worldmodeling_reward_weight: 100
        env_id: "AlignTwoCube" # AlignTwoCube,PlaceTwoCube,PutAppleInDrawer,StackThreeCube
    train_size: 10000  
    test_size: 4
env2:
    env_name: primitive_skill 
    env_config:
        render_mode: vision
        prompt_format: grounding_worldmodeling_structured
        use_state_reward: true
        grounding_reward_weight: 100
        worldmodeling_reward_weight: 100
        env_id: "PlaceTwoCube" # AlignTwoCube,PlaceTwoCube,PutAppleInDrawer,StackThreeCube
    train_size: 10000  
    test_size: 4
env3:
    env_name: primitive_skill 
    env_config:
        render_mode: vision
        prompt_format: grounding_worldmodeling_structured
        use_state_reward: true
        grounding_reward_weight: 100
        worldmodeling_reward_weight: 100
        env_id: "PutAppleInDrawer" # AlignTwoCube,PlaceTwoCube,PutAppleInDrawer,StackThreeCube
    train_size: 10000  
    test_size: 4
env4:
    env_name: primitive_skill 
    env_config:
        render_mode: vision
        prompt_format: grounding_worldmodeling_structured
        use_state_reward: true
        grounding_reward_weight: 100
        worldmodeling_reward_weight: 100
        env_id: "StackThreeCube" # AlignTwoCube,PlaceTwoCube,PutAppleInDrawer,StackThreeCube
    train_size: 10000  
    test_size: 4
