env1:
    env_name: primitive_skill 
    env_config:
        render_mode: vision
        prompt_format: grounding_worldmodeling
        use_state_reward: false
        env_id: "AlignTwoCube" # AlignTwoCube,PlaceTwoCube,PutAppleInDrawer,StackThreeCube
    train_size: 10000  
    test_size: 8
env2:
    env_name: primitive_skill 
    env_config:
        render_mode: vision
        prompt_format: grounding_worldmodeling
        use_state_reward: false
        env_id: "PlaceTwoCube" # AlignTwoCube,PlaceTwoCube,PutAppleInDrawer,StackThreeCube
    train_size: 10000  
    test_size: 8
env3:
    env_name: primitive_skill 
    env_config:
        render_mode: vision
        prompt_format: grounding_worldmodeling
        use_state_reward: false
        env_id: "PutAppleInDrawer" # AlignTwoCube,PlaceTwoCube,PutAppleInDrawer,StackThreeCube
    train_size: 10000  
    test_size: 8
env4:
    env_name: primitive_skill 
    env_config:
        render_mode: vision
        prompt_format: grounding_worldmodeling
        use_state_reward: false
        env_id: "StackThreeCube" # AlignTwoCube,PlaceTwoCube,PutAppleInDrawer,StackThreeCube
    train_size: 10000  
    test_size: 8
