env1:
    env_name: frozenlake  
    env_config:
        render_mode: vision
        prompt_format: grounding_worldmodeling_structured
        use_accuracy_reward: false
    train_size: 10000  
    test_size: 128