env1:
    env_name: navigation  
    env_config:
        render_mode: vision
        prompt_format: free_think
        use_accuracy_reward: false
        eval_set: base
    train_size: 10000  
    test_size: 2

env2:
    env_name: navigation  
    env_config:
        render_mode: vision
        prompt_format: free_think
        use_accuracy_reward: false
        eval_set: common_sense
    train_size: 10000  
    test_size: 2